name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
    if: >-
      !contains(fromJSON('["Production – theme-nextjs-bea-cookbook", "Production – theme-nextjs-bea-photography", "Production – theme-nextjs-bea-preview", "Production – theme-nextjs-bea-the-good-newsroom"]'), github.event.deployment.environment)
    uses: prezly/theme-kit-js/.github/workflows/playwright.shared.yml@main
    with:
      site-name: 'Preview Env'

